baseURL = 'https://pouroverdata.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
 title = "Pour over data blog"
 author = "EY"
 description = "blog to share my thoughts and projects "
 profilePicture = "images/pour_over_coffee.jpg"
 mainSections = ["blog"]

